"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-07 13:24:05.373814
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mappings",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("input_format", sa.String(length=20), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
        sa.UniqueConstraint("name", "revision", name="uq_mappings_name_revision"),
    )
    op.create_table(
        "raw_files",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("sha256"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("agent", sa.String(length=100), nullable=True),
        sa.Column("repo", sa.String(length=300), nullable=True),
        sa.Column("user", sa.String(length=300), nullable=True),
        sa.Column(
            "declared_started_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "declared_ended_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "observed_start_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column("observed_end_at", sa.DateTime(), nullable=True),
        sa.Column("model_call_count", sa.Integer(), nullable=False),
        sa.Column("tool_call_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_sessions_source_external_id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_agent", ["agent"], unique=False)

    op.create_table(
        "sources",
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("namespace"),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("mapping_id", sa.String(length=40), nullable=False),
        sa.Column("mapping_name", sa.String(length=200), nullable=False),
        sa.Column("mapping_revision", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("records", sa.JSON(), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("reject_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["mappings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.create_index("ix_imports_started_at", ["started_at"], unique=False)

    op.create_table(
        "raw_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("locator", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_sha256"],
            ["raw_files.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_sha256", "locator", name="uq_raw_records_locator"),
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("preview", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sha256"],
            ["raw_files.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_files",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("import_id", sa.String(length=40), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sha256"],
            ["raw_files.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_files", schema=None) as batch_op:
        batch_op.create_index("ix_import_files_sha256", ["sha256"], unique=False)

    op.create_table(
        "model_calls",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("import_id", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("occurrence_key", sa.String(length=400), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("locator", sa.String(length=64), nullable=False),
        sa.Column("emission_path", sa.String(length=200), nullable=False),
        sa.Column("native_key", sa.JSON(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("token_semantics", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_creation_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "occurrence_key", name="uq_model_calls_occurrence"),
    )
    with op.batch_alter_table("model_calls", schema=None) as batch_op:
        batch_op.create_index("ix_model_calls_session", ["session_id"], unique=False)

    op.create_table(
        "record_results",
        sa.Column("import_id", sa.String(length=40), nullable=False),
        sa.Column("locator", sa.String(length=64), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("entity_counts", sa.JSON(), nullable=False),
        sa.Column("warning_counts", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_sha256"],
            ["raw_files.sha256"],
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.PrimaryKeyConstraint("import_id", "locator"),
    )
    op.create_table(
        "rejects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("import_id", sa.String(length=40), nullable=False),
        sa.Column("locator", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rejects", schema=None) as batch_op:
        batch_op.create_index("ix_rejects_import_code", ["import_id", "code"], unique=False)

    op.create_table(
        "session_diagnostics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("import_id", sa.String(length=40), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("locator", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("model_call_id", sa.String(length=40), nullable=True),
        sa.Column("import_id", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("occurrence_key", sa.String(length=400), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("locator", sa.String(length=64), nullable=False),
        sa.Column("emission_path", sa.String(length=200), nullable=False),
        sa.Column("native_key", sa.JSON(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=True),
        sa.Column("tool_name", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("wall_latency_ms", sa.Integer(), nullable=True),
        sa.Column("internal_latency_ms", sa.Integer(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["model_calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "occurrence_key", name="uq_tool_calls_occurrence"),
    )
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.create_index("ix_tool_calls_model_call", ["model_call_id"], unique=False)
        batch_op.create_index("ix_tool_calls_session", ["session_id"], unique=False)

    op.create_table(
        "entity_contributions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("import_id", sa.String(length=40), nullable=False),
        sa.Column("mapping_id", sa.String(length=40), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("locator", sa.String(length=64), nullable=False),
        sa.Column("emission_path", sa.String(length=200), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=True),
        sa.Column("model_call_id", sa.String(length=40), nullable=True),
        sa.Column("tool_call_id", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "(session_id IS NOT NULL) + (model_call_id IS NOT NULL)"
            " + (tool_call_id IS NOT NULL) = 1",
            name="ck_contribution_exactly_one_entity",
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["imports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mapping_id"],
            ["mappings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["model_calls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entity_contributions", schema=None) as batch_op:
        batch_op.create_index("ix_contributions_session", ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entity_contributions", schema=None) as batch_op:
        batch_op.drop_index("ix_contributions_session")

    op.drop_table("entity_contributions")
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.drop_index("ix_tool_calls_session")
        batch_op.drop_index("ix_tool_calls_model_call")

    op.drop_table("tool_calls")
    op.drop_table("session_diagnostics")
    with op.batch_alter_table("rejects", schema=None) as batch_op:
        batch_op.drop_index("ix_rejects_import_code")

    op.drop_table("rejects")
    op.drop_table("record_results")
    with op.batch_alter_table("model_calls", schema=None) as batch_op:
        batch_op.drop_index("ix_model_calls_session")

    op.drop_table("model_calls")
    with op.batch_alter_table("import_files", schema=None) as batch_op:
        batch_op.drop_index("ix_import_files_sha256")

    op.drop_table("import_files")
    op.drop_table("uploads")
    op.drop_table("raw_records")
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.drop_index("ix_imports_started_at")

    op.drop_table("imports")
    op.drop_table("sources")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_agent")

    op.drop_table("sessions")
    op.drop_table("raw_files")
    op.drop_table("mappings")
    # ### end Alembic commands ###
