"""import files source and committed uniqueness

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-07 13:37:22.733059
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_files", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source", sa.String(length=100), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("committed", sa.Boolean(), nullable=False, server_default=sa.text("0"))
        )
        batch_op.create_index(
            "uq_import_files_committed_source",
            ["sha256", "source"],
            unique=True,
            sqlite_where=sa.text("committed = 1"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_files", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_import_files_committed_source", sqlite_where=sa.text("committed = 1")
        )
        batch_op.drop_column("committed")
        batch_op.drop_column("source")

    # ### end Alembic commands ###
